version: '3.8' # Specify docker-compose version

services:
  web:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: smukfest-app-compose # Optional: Give the container a specific name
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      # 1. Named volume for persistent data in /app (incl. DB)
      - smukfest_db_data:/app 
      # 2. Code mounts for hot-reload (overwrites code inside /app)
      - ./app:/app/app 
      - ./scripts:/app/scripts
    env_file:
      - .env # Load environment variables from the .env file in the project root
    # The command is taken from the Dockerfile CMD instruction.
    # You could override it here if needed, e.g.:
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 

volumes:
  smukfest_db_data: 