version: '3.8' # Specify docker-compose version

services:
  traefik:
    image: traefik:v3.1.0
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=mikkelkrogsholm@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"

  smukrisiko:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smukrisiko
    restart: always
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./scripts:/app/scripts
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smukrisiko.rule=Host(`risiko.smukfest.dk`)"
      - "traefik.http.routers.smukrisiko.entrypoints=websecure"
      - "traefik.http.routers.smukrisiko.tls.certresolver=myresolver"
      - "traefik.http.services.smukrisiko.loadbalancer.server.port=8000"
      - "traefik.http.routers.smukrisiko.middlewares=smukrisiko-sslheader"
      - "traefik.http.middlewares.smukrisiko-sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

volumes:
  letsencrypt: