"""Add ondelete=CASCADE to RiskAssessment.artist_slug

Revision ID: 2aded1f73546
Revises: cd749f90c588
Create Date: 2025-05-01 18:28:55.016788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aded1f73546'
down_revision: Union[str, None] = 'cd749f90c588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema using batch mode for SQLite compatibility."""
    # ### commands auto generated by Alembic - adjusted for batch mode ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_risk_assessments_artist_slug_artists_cascade', # Provide a new constraint name
            'artists', 
            ['artist_slug'], 
            ['slug'], 
            ondelete='CASCADE'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema using batch mode for SQLite compatibility."""
    # ### commands auto generated by Alembic - adjusted for batch mode ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_risk_assessments_artist_slug_artists_cascade', type_='foreignkey') # Drop the cascade constraint
    # ### end Alembic commands ###
